### ISSUE TITLE
_design in design document name

### ISSUE THREAD

**Issue by jamesnocentini** [couchbaselabs/ng-couchbase-lite#3]
The `createDesignDocument` and `queryView` methods require the design document name to be of the form `_design/{name}`. Removing the requirement to have `_design/` would make it simpler to use.

**Comment by swaheed2** [comment]
created pull request https://github.com/couchbaselabs/ng-couchbase-lite/pull/14 if author accepts.

Added backwards compatibility check for those already using "_design/designDocumentName"

**Comment by nraboy** [comment]
Merged
