### ISSUE TITLE
need documentation with example for all available methods..

### ISSUE THREAD

**Issue by faraazc** [couchbaselabs/ng-couchbase-lite#4]
What is difference between design document and document?..

**Comment by nraboy** [comment]
Design documents are for Couchbase Lite Views:

http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/view/index.html

Documents are NoSQL objects composed of JSON.

ng-couchbase-lite is only a wrapper for the Couchbase Lite RESTful API.  Documentation for this API can be seen here:

http://developer.couchbase.com/documentation/mobile/current/develop/references/couchbase-lite/rest-api/index.html

Best,
