### ISSUE TITLE
can we add a getter for databaseUrl to use the makeRequest function

### ISSUE THREAD

**Issue by swaheed2** [couchbaselabs/ng-couchbase-lite#8]
I was  trying to monitor progress using GET /_active_tasks and realized in order to to use the makeRequest function, I need database url. We already provided it to the factory when we did:

database = new $couchbase(url, appDbName);  

Why not have  it available for later use like database.getUrl()

**Comment by nraboy** [comment]
I agree with you, it wouldn't be a bad idea to have a `.getUrl()` function.  Would you like me to add it or would you like to create a PR for it?

**Comment by swaheed2** [comment]
Thank you for letting me contribute. 

https://github.com/couchbaselabs/ng-couchbase-lite/pull/12
